### ISSUE TITLE
Fixing DXF Polylines

### ISSUE THREAD

**Issue by danmarshall** [mdales/Fretboard-etching#1]
Hi @mdales - this is brilliant! Glad that you made excellent use of Maker.js. I agree the DXF export is simplistic, can you please give me details on how you expect polylines to work?

**Comment by mdales** [comment]
@danmarshall thanks, and thanks (I presume) for your work on maker.js - made this a lot easier than I thought it might!

I'm not really an expert of DXF, but what I want to be able to do is generate rectangles that are seen as closed by the laser script software on the laser cutter I use. The first time I did a fretboard this way I used Cut 2D to generate the small rectangles, exported the design as DXF, and then the laser software saw them as closed and let me etch them. With the output of this fretboard tool I have to tell the laser script software to find near points and create geometries from them.

At a high level Maker.js interaface I'd like a way of creating a rectangle and exporting as a poly line rather than as a series of four lines (see line 128 of fretboard-generator.js for where I create the rect). 

Obviously that's a bit specific, for my use case, but given how you do compositions of objects, just a way to create a series of lines (and perhaps automatically close?). Or just a final pass as per most CAD tools that lets you close geometries before exporting?

As a random aside, I think this tool might be a useful example of where the parameterisation power of maker.js isn't something I could take advantage of (at least not obvious). You'll see that the fret spacing follows a fairly simple rule, but it's no linear, so I couldn't use the power of Maker.js parameterisation as I probably should. And I've been too caught up in the physcial production aspects to go back and see how hard it'd be to modify maker.js to let you provide say an anonymous function as part of the normal maker.js flow.

Thanks again!

**Comment by danmarshall** [comment]
I've an issue to track DXF polylines: https://github.com/Microsoft/maker.js/issues/314
There is already code that looks for closed geometries for other export file formats, so the only detail I need to add is how to do it in DXF.

Can I ask further what you mean by parameterization? I see that you pass in a [params object](https://github.com/mdales/Fretboard-etching/blob/master/fretboard-generator.js#L97). That seems fine to me.

**Comment by danmarshall** [comment]
Hi Michael, did you get a chance to try out the new Polyline export feature? It works with most of my CAD apps. Does it work for the app that you read DXF?

**Comment by mdales** [comment]
Apologies for the slow response @danmarshall, I was hoping to get some more guitars built before now. Anyway, I've updated my tool and I can confirm it works exactly as I need! Many thanks!
